name: Lint
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
  merge_group:
  workflow_dispatch:
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: |
            *.md,
            docs/**/*.md
            template/README.md
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.21.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

