name: Lint
on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
  merge_group:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Lint
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: |
            *.md,
            docs/**/*.md
            template/README.md
